server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/mcffjr/microservices-exemplo/tree/master/config/
          search-paths: auth